version: "3.9"
services:
  jupyterLab:
    image: jupyter/datascience-notebook
    command: start.sh jupyter lab --LabApp.token=''
    ports:
      - 8088:8888
    volumes:
      - $PROJECT_DIR/notebooks:/home/jovyan/work